config/routes.rb
TestDistributedBuild::Application.routes.draw do
  resources :test_distrubuted_builds

end

app/models/test_distrubuted_build.rb
class TestDistrubutedBuild < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/test_distrubuted_builds_controller.rb
class TestDistrubutedBuildsController < ApplicationController
  # GET /test_distrubuted_builds
  # GET /test_distrubuted_builds.json
  def index
    @test_distrubuted_builds = TestDistrubutedBuild.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_distrubuted_builds }
    end
  end

  # GET /test_distrubuted_builds/1
  # GET /test_distrubuted_builds/1.json
  def show
    @test_distrubuted_build = TestDistrubutedBuild.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_distrubuted_build }
    end
  end

  # GET /test_distrubuted_builds/new
  # GET /test_distrubuted_builds/new.json
  def new
    @test_distrubuted_build = TestDistrubutedBuild.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_distrubuted_build }
    end
  end

  # GET /test_distrubuted_builds/1/edit
  def edit
    @test_distrubuted_build = TestDistrubutedBuild.find(params[:id])
  end

  # POST /test_distrubuted_builds
  # POST /test_distrubuted_builds.json
  def create
    @test_distrubuted_build = TestDistrubutedBuild.new(params[:test_distrubuted_build])

    respond_to do |format|
      if @test_distrubuted_build.save
        format.html { redirect_to @test_distrubuted_build, notice: 'Test distrubuted build was successfully created.' }
        format.json { render json: @test_distrubuted_build, status: :created, location: @test_distrubuted_build }
      else
        format.html { render action: "new" }
        format.json { render json: @test_distrubuted_build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_distrubuted_builds/1
  # PUT /test_distrubuted_builds/1.json
  def update
    @test_distrubuted_build = TestDistrubutedBuild.find(params[:id])

    respond_to do |format|
      if @test_distrubuted_build.update_attributes(params[:test_distrubuted_build])
        format.html { redirect_to @test_distrubuted_build, notice: 'Test distrubuted build was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_distrubuted_build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_distrubuted_builds/1
  # DELETE /test_distrubuted_builds/1.json
  def destroy
    @test_distrubuted_build = TestDistrubutedBuild.find(params[:id])
    @test_distrubuted_build.destroy

    respond_to do |format|
      format.html { redirect_to test_distrubuted_builds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_distrubuted_builds_helper.rb
module TestDistrubutedBuildsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestDistributedBuild</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/test_distrubuted_builds/_form.html.erb
<%= form_for(@test_distrubuted_build) do |f| %>
  <% if @test_distrubuted_build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_distrubuted_build.errors.count, "error") %> prohibited this test_distrubuted_build from being saved:</h2>

      <ul>
      <% @test_distrubuted_build.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_distrubuted_builds/edit.html.erb
<h1>Editing test_distrubuted_build</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_distrubuted_build %> |
<%= link_to 'Back', test_distrubuted_builds_path %>

app/views/test_distrubuted_builds/index.html.erb
<h1>Listing test_distrubuted_builds</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_distrubuted_builds.each do |test_distrubuted_build| %>
  <tr>
    <td><%= link_to 'Show', test_distrubuted_build %></td>
    <td><%= link_to 'Edit', edit_test_distrubuted_build_path(test_distrubuted_build) %></td>
    <td><%= link_to 'Destroy', test_distrubuted_build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test distrubuted build', new_test_distrubuted_build_path %>

app/views/test_distrubuted_builds/new.html.erb
<h1>New test_distrubuted_build</h1>

<%= render 'form' %>

<%= link_to 'Back', test_distrubuted_builds_path %>

app/views/test_distrubuted_builds/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_test_distrubuted_build_path(@test_distrubuted_build) %> |
<%= link_to 'Back', test_distrubuted_builds_path %>